ALTER TABLE loja_mercado_livre ADD last_updated timestamp NULL DEFAULT CURRENT_TIMESTAMP;
DROP TABLE db_analize.pedidos_pagamentos_mercado_livre;
DROP TABLE db_analize.pedidos_itens_mercado_livre;
DROP TABLE db_analize.pedidos_mercado_livre;

CREATE TABLE IF NOT EXISTS `pedidos_mercado_livre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` varchar(255) NOT NULL,
  `ml_order_id` varchar(255) NOT NULL UNIQUE,
  `fulfilled` tinyint(1) DEFAULT NULL,
  `expiration_date` timestamp NULL DEFAULT NULL,
  `date_closed` timestamp NULL DEFAULT NULL,
  `last_updated` timestamp NULL DEFAULT NULL,
  `date_created` timestamp NULL DEFAULT NULL,
  `manufacturing_ending_date` timestamp NULL DEFAULT NULL,
  `shipping_id` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT NULL,
  `paid_amount` decimal(10,2) DEFAULT NULL,
  `data_atualizacao` timestamp NULL DEFAULT NULL,
  `data_insercao` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`, `ml_order_id`),
  CONSTRAINT `pedidos_mercado_livre_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `loja_mercado_livre` (`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  UNIQUE INDEX `ml_order_id_UNIQUE` (`ml_order_id` ASC) VISIBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE IF NOT EXISTS `pedidos_itens_mercado_livre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` varchar(255) NOT NULL,
  `ml_order_id` varchar(255) NOT NULL,
  `seq` int NOT NULL,
  `ml_item_id` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `category_id` varchar(255) NOT NULL,
  `variation_id` varchar(255) NOT NULL,
  `seller_custom_field` varchar(255) DEFAULT NULL,
  `global_price` decimal(10,2) DEFAULT '0.00',
  `net_weight` varchar(255) DEFAULT NULL,
  `warranty` varchar(255) DEFAULT NULL,
  `condition_item` varchar(255) DEFAULT NULL,
  `seller_sku` varchar(255) DEFAULT NULL,
  `quantity` decimal(10,0) DEFAULT NULL,
  `unit_price` decimal(10,2) DEFAULT '0.00',
  `full_unit_price` decimal(10,2) DEFAULT '0.00',
  `currency_id` varchar(255) DEFAULT NULL,
  `manufacturing_days` varchar(255) DEFAULT NULL,
  `picked_quantity` varchar(255) DEFAULT NULL,
  `listing_type_id` varchar(255) DEFAULT NULL,
  `base_exchange_rate` varchar(255) DEFAULT NULL,
  `base_currency_id` varchar(255) DEFAULT NULL,
  `bundle` varchar(255) DEFAULT NULL,
  `element_id` varchar(255) DEFAULT NULL,
  `data_atualizacao` timestamp NULL DEFAULT NULL,
  `data_insercao` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`, `ml_order_id`),
  CONSTRAINT `pedidos_itens_mercado_livre_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `pedidos_mercado_livre` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `pedidos_itens_mercado_livre_ibfk_2` FOREIGN KEY (`ml_order_id`) REFERENCES `pedidos_mercado_livre` (`ml_order_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE IF NOT EXISTS `pedidos_pagamentos_mercado_livre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` varchar(255) NOT NULL,
  `ml_order_id` varchar(255) NOT NULL,
  `payment_id` varchar(255) NOT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `status_code` varchar(255) DEFAULT NULL,
  `total_paid_amount` varchar(255) DEFAULT NULL,
  `operation_type` varchar(255) DEFAULT NULL,
  `transaction_amount` varchar(255) DEFAULT NULL,
  `transaction_amount_refunded` int DEFAULT NULL,
  `date_approved` varchar(255) DEFAULT NULL,
  `collector_id` varchar(255) DEFAULT NULL,
  `coupon_id` varchar(255) DEFAULT NULL,
  `installments` int DEFAULT NULL,
  `authorization_code` varchar(255) DEFAULT NULL,
  `taxes_amount` varchar(255) DEFAULT NULL,
  `date_last_modified` varchar(255) DEFAULT NULL,
  `coupon_amount` varchar(255) DEFAULT NULL,
  `shipping_cost` varchar(255) DEFAULT NULL,
  `installment_amount` varchar(255) DEFAULT NULL,
  `date_created` varchar(255) DEFAULT NULL,
  `activation_uri` varchar(255) DEFAULT NULL,
  `overpaid_amount` varchar(255) DEFAULT NULL,
  `card_id` varchar(255) DEFAULT NULL,
  `status_detail` varchar(255) DEFAULT NULL,
  `issuer_id` varchar(255) DEFAULT NULL,
  `payment_method_id` varchar(255) DEFAULT NULL,
  `payment_type` varchar(255) DEFAULT NULL,
  `deferred_period` varchar(255) DEFAULT NULL,
  `atm_transfer_reference_transaction_id` varchar(255) DEFAULT NULL,
  `atm_transfer_reference_company_id` varchar(255) DEFAULT NULL,
  `site_id` varchar(255) DEFAULT NULL,
  `payer_id` bigint DEFAULT NULL,
  `order_id` bigint DEFAULT NULL,
  `currency_id` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `transaction_order_id` varchar(255) DEFAULT NULL,
  `data_atualizacao` timestamp NULL DEFAULT NULL,
  `data_insercao` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`,`ml_order_id`),
  CONSTRAINT `pedidos_pagamentos_mercado_livre_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `pedidos_mercado_livre` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `pedidos_pagamentos_mercado_livre_ibfk_2` FOREIGN KEY (`ml_order_id`) REFERENCES `pedidos_mercado_livre` (`ml_order_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE IF NOT EXISTS `pedidos_envios_mercado_livre` (
	`id` INT NOT NULL AUTO_INCREMENT,
    `user_id` VARCHAR(255) NOT NULL,
	`ml_order_id` VARCHAR(255) NOT NULL,
    `substatus_history` VARCHAR(255) NULL,
    `snapshot_packing` VARCHAR(45) NULL,
    `receiver_id` VARCHAR(255) NOT NULL,
    `base_cost` DECIMAL(4, 2),
    `type` VARCHAR(45) NOT NULL,
    `return_details` VARCHAR(45) NULL,
    `sender_id` VARCHAR(255) NOT NULL,
    `mode` VARCHAR(45) NOT NULL,
    `order_cost` DECIMAL(4, 2),
    `priority_class` VARCHAR(45) NULL,
    `service_id` VARCHAR(45) NULL,
    `tracking_number` VARCHAR(45) NOT NULL,
    `shipping_id` VARCHAR(255) NOT NULL,
    `tracking_method` VARCHAR(45) NOT NULL,
    `last_updated` timestamp NULL DEFAULT NULL,
    `items_types` VARCHAR(255) NULL,
    `comments` VARCHAR(255) NULL,
    `substatus` VARCHAR(255) NULL,
    `date_created` timestamp NULL DEFAULT NULL,
    `date_first_printed` timestamp NULL DEFAULT NULL,
    `created_by` VARCHAR(45) NULL,
    `application_id` VARCHAR(45) NULL,
    `return_tracking_number` VARCHAR(45) NULL,
    `site_id` VARCHAR(45) NOT NULL,
    `carrier_info` VARCHAR(45) NULL,
    `market_place` VARCHAR(45) NULL,
    `customer_id` VARCHAR(45) NULL,
    `quotation` VARCHAR(255) NULL,
    `status` VARCHAR(45) NULL,
    `logistic_type` VARCHAR(255) null,
    `data_atualizacao` timestamp NULL DEFAULT NULL,
  	`data_insercao` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  	PRIMARY KEY (`id`, `user_id`,`ml_order_id`),
  	CONSTRAINT `pedidos_envios_mercado_livre_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `pedidos_mercado_livre` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  	CONSTRAINT `pedidos_envios_mercado_livre_ibfk_2` FOREIGN KEY (`ml_order_id`) REFERENCES `pedidos_mercado_livre` (`ml_order_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;